version: "3.5"

services:
  contrataciones_estado:
    build: ./src
    restart: no
    volumes:
      - ./config/:/app/config
      - ./inputs/:/app/inputs
      - ./outputs/:/app/outputs
      - ./archive/:/app/archive
      - ./log/:/log
    networks:
      - networkCommon

networks:
  networkCommon:
    driver: bridge
    name: networkCommon
